import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, Section } from "@/components/LegalPage";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — CoraHQ" },
      { name: "description", content: "The plain-language terms for using CoraHQ, the AI-search visibility and optimization tool for YouTube creators." },
      { property: "og:title", content: "Terms of Service — CoraHQ" },
      { property: "og:description", content: "Accounts, billing, acceptable use, AI-output disclaimers and liability terms for CoraHQ." },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="1 August 2026"
      intro="These terms explain what CoraHQ does, what you can expect from us, and what we expect from you. By creating an account or paying for a plan you agree to them. CoraHQ is operated by Cora (“we”, “us”) at corahq.online."
    >
      <Section n={1} title="What the service does">
        <p>
          CoraHQ helps YouTube creators get cited by AI answer engines such as ChatGPT, Perplexity,
          Gemini and Claude. You submit video details — title, description, tags, transcript, or a
          channel URL — and we return a visibility score plus suggested titles, descriptions, FAQs
          and chapters designed to be easier for AI systems to quote.
        </p>
        <p>It is an analysis and writing tool. It does not post to YouTube or contact any AI provider on your behalf.</p>
      </Section>

      <Section n={2} title="Who can open an account">
        <ul>
          <li>You must be at least 18 years old.</li>
          <li>You must give accurate signup details and keep your email current.</li>
          <li>You are responsible for anything done through your account, so keep your login secure.</li>
          <li>One account per person or business unless we agree otherwise in writing.</li>
        </ul>
      </Section>

      <Section n={3} title="Plans, billing and renewal">
        <ul>
          <li>There is a free tier with limited access and a paid Pro tier.</li>
          <li>Pro is $25 per month or $125 per year. All prices are in USD and exclude any tax that Paddle adds at checkout.</li>
          <li>Payments are processed by Paddle.com, which acts as the merchant of record. Your receipt and invoices come from Paddle.</li>
          <li>Subscriptions renew automatically at the end of each billing period until you cancel.</li>
          <li>You can cancel anytime; access continues until the end of the period you have already paid for.</li>
          <li>We may change prices with at least 30 days' notice by email. Changes never apply to a period you have already paid for.</li>
        </ul>
      </Section>

      <Section n={4} title="Acceptable use">
        <p>Please don't:</p>
        <ul>
          <li>Scrape, crawl or bulk-extract the service, or automate it outside the normal interface.</li>
          <li>Reverse engineer, decompile or try to extract our prompts, models or source code.</li>
          <li>Resell, sublicense or share your access with people outside your account.</li>
          <li>Create multiple accounts to get around free-tier limits, rate limits or scan quotas.</li>
          <li>Submit content you don't have the rights to, or anything unlawful, hateful or infringing.</li>
          <li>Interfere with the service's availability or security.</li>
        </ul>
      </Section>

      <Section n={5} title="About AI-generated output">
        <p>
          Everything CoraHQ produces is a suggestion generated by an AI model. We do not guarantee
          that using it will get you cited, ranked, recommended or linked by ChatGPT, Gemini,
          Perplexity, Claude, Google or YouTube. Those systems are controlled by third parties and
          change without notice.
        </p>
        <p>
          Models can be wrong. Review every suggestion for accuracy, tone and rights before you
          publish it. You are responsible for what you publish on your own channel.
        </p>
      </Section>

      <Section n={6} title="Who owns what">
        <ul>
          <li>You keep all rights to the content you submit and to anything you publish based on our suggestions.</li>
          <li>You give us permission to store and process your submitted content so we can run the service, show your history and support you.</li>
          <li>We keep all rights to CoraHQ itself — the software, prompts, scoring logic, branding and site content.</li>
        </ul>
      </Section>

      <Section n={7} title="Ending the relationship">
        <ul>
          <li>You may stop using CoraHQ or delete your account at any time.</li>
          <li>We may suspend or close an account for abuse, non-payment, or a breach of these terms — usually after a warning where it's practical to give one.</li>
          <li>We may discontinue the service with reasonable notice; if we do, we'll refund the unused portion of any prepaid period.</li>
        </ul>
      </Section>

      <Section n={8} title="Service is provided “as is”">
        <p>
          CoraHQ is provided as is and as available, without warranties of any kind. We don't promise
          uninterrupted uptime, error-free output, or any specific business result.
        </p>
        <p>
          To the maximum extent the law allows, we are not liable for lost profits, lost views, lost
          revenue, lost data or any indirect or consequential loss. Where liability cannot be excluded,
          our total liability is limited to the amount you paid us in the 12 months before the claim.
        </p>
      </Section>

      <Section n={9} title="Governing law and disputes">
        <p>
          These terms are governed by the laws of India, and the courts of India have exclusive
          jurisdiction over any dispute. Before starting a formal claim, please email us — most
          issues are resolved quickly and informally.
        </p>
      </Section>

      <Section n={10} title="Questions">
        <p>
          Email <a href="mailto:hello@corahq.com">hello@corahq.com</a> and we'll get back to you.
          We may update these terms; material changes will be announced by email or an in-app notice,
          and the “last updated” date above will change.
        </p>
      </Section>
    </LegalPage>
  );
}
