/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOptimizeRouteImport } from './routes/_authenticated/optimize'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiWebhookPaddleRouteImport } from './routes/api/webhook/paddle'
import { Route as ApiPublicWebhookPaddleRouteImport } from './routes/api/public/webhook/paddle'
import { Route as ApiPublicHooksRefreshAlertsRouteImport } from './routes/api/public/hooks/refresh-alerts'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOptimizeRoute = AuthenticatedOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWebhookPaddleRoute = ApiWebhookPaddleRouteImport.update({
  id: '/api/webhook/paddle',
  path: '/api/webhook/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookPaddleRoute = ApiPublicWebhookPaddleRouteImport.update({
  id: '/api/public/webhook/paddle',
  path: '/api/public/webhook/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshAlertsRoute =
  ApiPublicHooksRefreshAlertsRouteImport.update({
    id: '/api/public/hooks/refresh-alerts',
    path: '/api/public/hooks/refresh-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/optimize': typeof AuthenticatedOptimizeRoute
  '/api/webhook/paddle': typeof ApiWebhookPaddleRoute
  '/api/public/hooks/refresh-alerts': typeof ApiPublicHooksRefreshAlertsRoute
  '/api/public/webhook/paddle': typeof ApiPublicWebhookPaddleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/optimize': typeof AuthenticatedOptimizeRoute
  '/api/webhook/paddle': typeof ApiWebhookPaddleRoute
  '/api/public/hooks/refresh-alerts': typeof ApiPublicHooksRefreshAlertsRoute
  '/api/public/webhook/paddle': typeof ApiPublicWebhookPaddleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/optimize': typeof AuthenticatedOptimizeRoute
  '/api/webhook/paddle': typeof ApiWebhookPaddleRoute
  '/api/public/hooks/refresh-alerts': typeof ApiPublicHooksRefreshAlertsRoute
  '/api/public/webhook/paddle': typeof ApiPublicWebhookPaddleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/refund-policy'
    | '/terms'
    | '/welcome'
    | '/alerts'
    | '/dashboard'
    | '/optimize'
    | '/api/webhook/paddle'
    | '/api/public/hooks/refresh-alerts'
    | '/api/public/webhook/paddle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/refund-policy'
    | '/terms'
    | '/welcome'
    | '/alerts'
    | '/dashboard'
    | '/optimize'
    | '/api/webhook/paddle'
    | '/api/public/hooks/refresh-alerts'
    | '/api/public/webhook/paddle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/refund-policy'
    | '/terms'
    | '/welcome'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/optimize'
    | '/api/webhook/paddle'
    | '/api/public/hooks/refresh-alerts'
    | '/api/public/webhook/paddle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiWebhookPaddleRoute: typeof ApiWebhookPaddleRoute
  ApiPublicHooksRefreshAlertsRoute: typeof ApiPublicHooksRefreshAlertsRoute
  ApiPublicWebhookPaddleRoute: typeof ApiPublicWebhookPaddleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/optimize': {
      id: '/_authenticated/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof AuthenticatedOptimizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhook/paddle': {
      id: '/api/webhook/paddle'
      path: '/api/webhook/paddle'
      fullPath: '/api/webhook/paddle'
      preLoaderRoute: typeof ApiWebhookPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/paddle': {
      id: '/api/public/webhook/paddle'
      path: '/api/public/webhook/paddle'
      fullPath: '/api/public/webhook/paddle'
      preLoaderRoute: typeof ApiPublicWebhookPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-alerts': {
      id: '/api/public/hooks/refresh-alerts'
      path: '/api/public/hooks/refresh-alerts'
      fullPath: '/api/public/hooks/refresh-alerts'
      preLoaderRoute: typeof ApiPublicHooksRefreshAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOptimizeRoute: typeof AuthenticatedOptimizeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOptimizeRoute: AuthenticatedOptimizeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  ApiWebhookPaddleRoute: ApiWebhookPaddleRoute,
  ApiPublicHooksRefreshAlertsRoute: ApiPublicHooksRefreshAlertsRoute,
  ApiPublicWebhookPaddleRoute: ApiPublicWebhookPaddleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
